### PR TITLE
fixed header

### PR DESCRIPTION
**Pull request by martinjc**
This fulfils the functional requirements of https://github.com/drvinceknight/tex/issues/15 if not the quality requirements of the issue title (I suspect this is far from perfect).

Uses [position:sticky](https://caniuse.com/#search=position%3A%20sticky) which is pretty well supported, but I have not tested this in anything other than latest Chrome and Firefox.

### CODE REVIEW

**Comment by drvinceknight** [comment]
Thanks for this @martinjc: really appreciate it :) :+1:

**Comment by martinjc** [comment]
No problem. I'll have a play and actually get the menu to work properly and let you know once it's ready

**Comment by martinjc** [comment]
okay. think those commits fix things. 

sets a height on the nav menu when it's opened which allows the menu to scroll
adds a bit of js to listen for click events in the menu to close it again when clicked
adds some extra (but hidden) space above the titles so they appear below the fixed header

(also relocates the final div which had snuck outside the body)

works in firefox and chrome here on my machine. not tested anywhere else ;-)

**Comment by drvinceknight** [comment]
Awesome! Thanks @martinjc all hail your knowledge of the dark arts.

**Pull request merged**
